### ISSUE TITLE
Styles are not available

### ISSUE THREAD

**Issue by tdonhauser** [alexrabin/vite-ssr-styled-components#1]
Hello,

I tried to test your approach, but with this the option "stryled-components" in noExternal in the vite.config.ts like this 

```
import react from '@vitejs/plugin-react'
import vike from 'vike/plugin'

export default ({
  plugins: [react(), vike({ prerender: true })],
  ssr: {
    noExternal: ["styled-components", "@emotion/*"]
  }
})
```

I can not get it to run. The page flickers with no styles when a client tries to load it. When I leave out the styled-components in noExternal it works for the development sever perfect but a get an error as you described in you post.

Any ideas how to solve this? Would be great. Thanks!

**Comment by alexrabin** [comment]
@der1igedon  I upgraded the package to the updated vike and the solution still works for me. What version of node are you using? I am on v20.4.0

**Comment by tdonhauser** [comment]
I use node version 20.8.6
Just for my understanding: Why is it not possible to pack styled-components in the server-side rendered bundle. If we use noExternal Vite will treat specified dependencies as they are already available on the server or client-side. It makes sense that they are not available instantly... or am I wrong?

**Comment by alexrabin** [comment]
@der1igedon It is my understanding that styled components can only be rendered on the client.

https://styled-components.com/docs/advanced#server-side-rendering

**Comment by alexrabin** [comment]
@der1igedon were you able to build the vite app?

**Comment by tdonhauser** [comment]
I have no problem building the app and running the server. The problem is the first render behaviour.
My page should look like this:

![image](https://github.com/alexrabin/vite-ssr-styled-components/assets/21998742/d24ae325-593b-476a-a79b-def7b181ee26)

The header and footer are part of a pageshell and styled using styled components. When I load the page (with styled-components in noExternal) the first render looks like this:

![image](https://github.com/alexrabin/vite-ssr-styled-components/assets/21998742/03fafeb6-fd59-4853-b9cc-6a221d59b3b7)

If I remove styled-components from noExternal. The first render looks like this:

![image](https://github.com/alexrabin/vite-ssr-styled-components/assets/21998742/f2b5efe9-1d24-469d-b36a-8107581b9b55)

What is the reason for that? Do you have any idea how to solve it?

**Comment by alexrabin** [comment]
@der1igedon Can you create a minimal example repo that I can pull and test on my machine?

**Comment by tdonhauser** [comment]
I tried to make an example with you repo, but I cant get it to run. If I just clone it run `npm run install` and `npm run dev` I get this error:

```
npm run dev

> dev
> npm run server


> server
> ts-node ./server/index.ts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/tdon/git/vite-ssr-styled-components/server/index.ts
    at new NodeError (node:internal/errors:406:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:99:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:142:36)
    at defaultLoad (node:internal/modules/esm/load:120:20)
    at nextLoad (node:internal/modules/esm/hooks:833:28)
    at load (/Users/tdon/git/vite-ssr-styled-components/node_modules/ts-node/dist/child/child-loader.js:19:122)
    at nextLoad (node:internal/modules/esm/hooks:833:28)
    at Hooks.load (node:internal/modules/esm/hooks:416:26)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

I use node version v20.8.0. Probably this has nothing to do with the styled-components problem...
I will setup another example and send it to you. Thanks a lot!

**Comment by alexrabin** [comment]
Yeah that is a node v20 problem. You can replace the dev command with this 
```
node --no-warnings=ExperimentalWarning --loader ts-node/esm ./server/index.ts
```

Sources:

https://github.com/vikejs/vike/issues/877#issuecomment-1676267953
https://github.com/TypeStrong/ts-node/issues/1997#issuecomment-1537111441

**Comment by tdonhauser** [comment]
Ahh perfect thanks!
I ran your code and it shows the same behaviour. I used google-chrome's performance insights and recorded the page load of your site. You can find the data to import and analyze here:

[pageLoad.json.gz](https://github.com/alexrabin/vite-ssr-styled-components/files/12910326/pageLoad.json.gz)

First the page (plain html) loads and no red background is visible. and with some time delay the red background is rendered. I guess this is not how it is supposed to be?

**Comment by tdonhauser** [comment]
I stumbeld on this post: https://github.com/styled-components/styled-components/issues/3700
Could this be related to the problem here?

**Comment by alexrabin** [comment]
@der1igedon the problem we are having is FOUS (flash of unstyled content) this is happening on dev too so I don’t think the noExternal is the problem. I’ll have some time this weekend to look into it more

**Comment by tdonhauser** [comment]
I found out something extra. I use grommet.io for my components. Grommet.io uses styled-components as well. But these are not found by getStyleText(). I made a small example based on your code:

https://github.com/der1igedon/vite-ssr-styled-components-grommet/tree/main/

**Comment by tdonhauser** [comment]
did you get a chance to look at the example?

**Comment by alexrabin** [comment]
@der1igedon I haven’t had any time lately. One way to mitigate this is to start off with the body with an opacity of 0 and wait until the styles have loaded and animate the opacity the 1. But that is more of a hack. I don’t have a solution at this moment.

**Comment by tdonhauser** [comment]
no problem. thanks for the idea!
do you know how I could implement a loading page as the pageshell that switches to the real page once its hydrated?

**Comment by alexrabin** [comment]
@der1igedon  here is an example. I created a branch: https://github.com/alexrabin/vite-ssr-styled-components/tree/fix/fous-loader

You can add some loader styles in the pageshell.css.
Some more loaders here: https://cssloaders.github.io
```css

.loader-box {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 99vh;
  width: 100%;
}
.loader {
  width: 48px;
  height: 48px;
  border: 5px solid #2593e1;
  border-bottom-color: transparent;
  border-radius: 50%;
  display: inline-block;
  box-sizing: border-box;
  animation: rotation 1s linear infinite;
}

@keyframes rotation {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
```

Then in the PageShell.tsx, you can add a loading state and use a useEffect with a timeout. Then use the loading state to display the spinner while the loading state is true.

```typescript
const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 2000); // Replace with an appropriate loading time
  }, []);

  if (loading) {
    return (
      <div className="loader-box">
        <span className="loader"></span>
      </div>
    );
  }
```

**Comment by tdonhauser** [comment]
Wow, thanks a lot!
But there's no way to get a signal once loading is complete. I have to do it with a timeout?

**Comment by alexrabin** [comment]
@der1igedon there probably is a way but I'd recommend using the timeout since you'd be able to control the specific loading time.

**Comment by tdonhauser** [comment]
I'm not sure, because the loading time usually depends on the network connection. That would mean I have to set it quite high to not have flickering on slow connections.

**Comment by alexrabin** [comment]
@der1igedon still looking into this. I'm trying to do something with babel but haven't had any success.

https://styled-components.com/docs/tooling#babel-plugin

```bash
npm i -D babel-plugin-styled-components
```

Then edit the react plugin in Vite.config.ts:

```typescript
react({
      babel: {
        babelrc: false,
        configFile: false,
        plugins: [
          [
            "babel-plugin-styled-components",
            {
              ssr: true,
            },
          ],
        ],
      },
    }),
```

**Comment by tdonhauser** [comment]
I've tried this before in a similar way. I installed babel-plugin-styled-components and created a file called `.babelrc` within the root directory with the following content:

```
{
  "plugins": [["styled-components", { "ssr": true }]]
}
```

Unfortunately that didn't change anything.

**Comment by alexrabin** [comment]
Did you add the set babelrc to true in the react plugin in the vite.config.js?

**Comment by tdonhauser** [comment]
No I didn't do anything there. What do I have to add there and what does it do?

**Comment by alexrabin** [comment]
```
react({
      babel: {
        babelrc: true,
      },
    }),
```

It tells vite to use the babelrc file.

**Comment by tdonhauser** [comment]
Ahh ok. Thanks. No, that didn't change anything unfortunately.

**Comment by ixdlh** [comment]
Hey guys, 
after having the same issue (FOUC) and questioning if SSR is working properly with styled-components i dug a bit and it seems the issue is related to 

`<style>${dangerouslySkipEscape(sheet.getStyleTags())}</style>`

Which results in something like
`<style><style data-styled="true" data-styled-version="5.3.9">.dSqtrW{width:100%;background-color:red;}/*!sc*/
data-styled.g1[id="indexpage__Container-sc-3rdsw7-0"]{content:"dSqtrW,"}/*!sc*/
</style>`

I.e encapsulating styled-components within a style tag. So just using `${dangerouslySkipEscape(sheet.getStyleTags())}` within `_default.page.server.tsx` head seems to resolve the issue and the content is rendered properly on the server.

Hope this helps and works for you ✌️

**Comment by alexrabin** [comment]
@ixdlh yep removing the unnecessary `style` tag fixed it. I pushed the change to the main branch
