### ISSUE TITLE
Cumulative layout shift issue

### ISSUE THREAD

**Issue by tom-leamon** [alexrabin/vite-ssr-styled-components#2]
This demo does not work properly. The styles from styled-components take like a half second to load once the page loads, causing a bad CLS. I've tried many combinations of using `babel-plugin-styled-components` in the `vite.config.ts`  but no luck. You should include a warning in your article so people don't waste their time until a viable solution has been found. Thanks!

**Comment by alexrabin** [comment]
Related #1 

Will update article accordingly when I have time.

**Comment by alexrabin** [comment]
Remove the `style` tag in the `head` element in `render/_default.page.server.tsx`. For example this is what the head element should look like now:

```html

 <head>
        <meta charset="UTF-8" />
        <link rel="icon" href="${logoUrl}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="${desc}" />
        <title>${title}</title>
        ${dangerouslySkipEscape(sheet.getStyleTags())}

      </head>
```
